import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getTimingData, markPageStart, getInitializedFrom } from '@/utils/timing'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  markPageStart()
  const timingData = getTimingData()
  // Initialize request counter (works for all pages)
  
  return (
    <html lang="en">
      <head>
        <meta name="x-request-count" content={timingData.requestCount.toString()} />
        <meta name="x-is-cold-start" content={timingData.isColdStart.toString()} />
        <meta name="x-instance-init-time" content={timingData.instanceInitTime.toString()} />
        <meta name="x-initialized-from" content={getInitializedFrom() || ''} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
